version: '3.3'
services:

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - front_net
      - back_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net
      - back_net
          
  mongodb-exporter:
    user: root
    image: bitnami/mongodb-exporter:latest
    container_name: mongodb-exporter
    networks:
      - front_net
      - back_net
    command:
      - '--mongodb.uri=post_db:27017'
      - '--web.listen-address=:9111'
      
  blackbox-exporter:
    user: root
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    networks:
      - front_net
      - back_net

  
  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - front_net
      - back_net

  grafana:
    image: grafana/grafana:5.0.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000    
    networks:
      - front_net
      - back_net
  
  alertmanager:
    image: ${USER_NAME}/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      - front_net
      - back_net

  telegraf:
    image: ${USER_NAME}/telegraf
    ports:
      - 9100:9100
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - back_net
      - front_net

volumes:
  prometheus_data: 
  grafana_data:

networks:
  back_net:
  front_net:
