version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_TAG}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  ui:
    env_file: .env
    image: ${USERNAME}/ui:${UI_TAG}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  post:
    image: ${USERNAME}/post:${POST_TAG}
    networks:
      - front_net
      - back_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  comment:
    image: ${USERNAME}/comment:${COMMENT_TAG}
    networks:
      - front_net
      - back_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    
volumes:
  post_db:   

networks:
  back_net:
  front_net:
