version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_TAG}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    env_file: .env
#    build: ./ui
    image: ${USER_NAME}/ui:${UI_TAG}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net
  post:
#    build: ./post-py
    image: ${USER_NAME}/post:${POST_TAG}
    networks:
      - front_net
      - back_net
  comment:
#    build: ./comment
    image: ${USER_NAME}/comment:${COMMENT_TAG}
    networks:
      - front_net
      - back_net

volumes:
  post_db:   

networks:
  back_net:
  front_net:
