{
 "title": "Telegraf metrics",
 "description": "Prometheus/victoriametrics dashboards for telegraf metrics",
 "tags": [
  "prometheus",
  "telegraf",
  "victoriametrics"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "server", "label": "Server", "query": "label_values(host)" },
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage by container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image",
     "col": "usage",
     "expr": "docker_container_cpu_usage_percent{host =~ \"$server$\"}",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}",
     "measurement": "docker_container_cpu",
     "query": "SELECT mean(\"usage_percent\") as \"usage\" FROM \"docker_container_cpu\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "RAM usage by container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image",
     "col": "usage",
     "expr": "docker_container_mem_usage_percent{host =~ \"$server$\"}",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}",
     "measurement": "docker_container_mem",
     "query": "SELECT mean(\"usage_percent\") as \"usage\" FROM \"docker_container_mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Network usage by container / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "rx",
     "expr": "abs(docker_container_net_rx_bytes{host =~ \"$server$\"})",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: rx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"),1s)/8 as \"rx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "tx",
     "expr": "abs(docker_container_net_tx_bytes{host =~ \"$server$\"})",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: tx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"),1s)/8 as \"tx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Network packets by container / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "rx",
     "expr": "abs(docker_container_net_rx_packets{host =~ \"$server$\"})",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: rx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_packets\"),1s) as \"rx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "rx_packets" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "tx",
     "expr": "abs(docker_container_net_tx_packets{host =~ \"$server$\"})",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: tx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"tx_packets\"),1s) as \"tx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "tx_packets" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Network dropped by container / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "rx",
     "expr": "abs(docker_container_net_rx_dropped{host =~ \"$server$\"})",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: rx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_dropped\"),1s) as \"rx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "rx_dropped" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "tx",
     "expr": "abs(docker_container_net_tx_dropped{host =~ \"$server$\"})",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: tx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"tx_dropped\"),1s) as \"tx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "tx_dropped" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Network errors by container / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "rx",
     "expr": "abs(docker_container_net_rx_errors{host =~ \"$server$\"})",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: rx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_errors\"),1s) as \"rx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "rx_errors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "tx",
     "expr": "abs(docker_container_net_tx_errors{host =~ \"$server$\"})",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: tx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"tx_errors\"),1s) as \"tx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "tx_errors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "NSQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Channel messages",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1462 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_channel - $tag_topic",
       "col": "messages",
       "expr": "median(nsq_channel_message_count{host =~ \"^$server$\"}) by (host,channel,topic)",
       "groupBy": " by (host,channel,topic)",
       "legendFormat": "{{host}}: {{channel}} - {{topic}}",
       "measurement": "nsq_channel",
       "query": "SELECT mean(\"message_count\") as \"messages\" FROM \"nsq_channel\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
       "select": [
        [
         { "params": [ "message_count" ], "type": "mean" }
        ]
       ],
       "tags": "{host =~ \"^$server$\"}"
      }
     ]
    },
    {
     "title": "Channel clients",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1462 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_channel - $tag_topic",
       "col": "client",
       "expr": "median(nsq_channel_client_count{host =~ \"^$server$\"}) by (host,channel,topic)",
       "groupBy": " by (host,channel,topic)",
       "legendFormat": "{{host}}: {{channel}} - {{topic}}",
       "measurement": "nsq_channel",
       "query": "SELECT mean(\"client_count\") as client FROM \"nsq_channel\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), * fill(null)",
       "select": [
        [
         { "params": [ "client_count" ], "type": "mean" }
        ]
       ],
       "tags": "{host =~ \"^$server$\"}"
      }
     ]
    },
    {
     "title": "Channel requeue",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1469 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_channel - $tag_topic",
       "expr": "median(nsq_channel_requeue_count{host =~ \"^$server$\"}) by (host,channel,topic)",
       "groupBy": " by (host,channel,topic)",
       "legendFormat": "{{host}}: {{channel}} - {{topic}}",
       "measurement": "nsq_channel",
       "query": "SELECT mean(\"requeue_count\") FROM \"nsq_channel\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), * fill(null)",
       "select": [
        [
         { "params": [ "requeue_count" ], "type": "mean" }
        ]
       ],
       "tags": "{host =~ \"^$server$\"}"
      }
     ]
    },
    {
     "title": "Channel inflight",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1469 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_channel - $tag_topic",
       "expr": "median(nsq_channel_inflight_count{host =~ \"^$server$\"}) by (host,channel,topic)",
       "groupBy": " by (host,channel,topic)",
       "legendFormat": "{{host}}: {{channel}} - {{topic}}",
       "measurement": "nsq_channel",
       "query": "SELECT mean(\"inflight_count\") FROM \"nsq_channel\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
       "select": [
        [
         { "params": [ "inflight_count" ], "type": "mean" }
        ]
       ],
       "tags": "{host =~ \"^$server$\"}"
      }
     ]
    },
    {
     "title": "Channel deferred",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1476 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_channel - $tag_topic",
       "col": "deferred",
       "expr": "median(nsq_channel_deferred_count{host =~ \"^$server$\"}) by (host,channel,topic)",
       "groupBy": " by (host,channel,topic)",
       "legendFormat": "{{host}}: {{channel}} - {{topic}}",
       "measurement": "nsq_channel",
       "query": "SELECT mean(\"deferred_count\") as \"deferred\" FROM \"nsq_channel\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), * fill(null)",
       "select": [
        [
         { "params": [ "deferred_count" ], "type": "mean" }
        ]
       ],
       "tags": "{host =~ \"^$server$\"}"
      }
     ]
    },
    {
     "title": "Channel timeout",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1476 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_channel - $tag_topic",
       "expr": "median(nsq_channel_timeout_count{host =~ \"^$server$\"}) by (host,channel,topic)",
       "groupBy": " by (host,channel,topic)",
       "legendFormat": "{{host}}: {{channel}} - {{topic}}",
       "measurement": "nsq_channel",
       "query": "SELECT mean(\"timeout_count\") FROM \"nsq_channel\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), * fill(null)",
       "select": [
        [
         { "params": [ "timeout_count" ], "type": "mean" }
        ]
       ],
       "tags": "{host =~ \"^$server$\"}"
      }
     ]
    },
    {
     "title": "Client messages",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1483 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_channel - $tag_topic",
       "col": "message",
       "expr": "median(nsq_client_message_count{host =~ \"^$server$\"}) by (host,channel,topic)",
       "groupBy": " by (host,channel,topic)",
       "legendFormat": "{{host}}: {{channel}} - {{topic}}",
       "measurement": "nsq_client",
       "query": "SELECT mean(\"message_count\") as \"message\" FROM \"nsq_client\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
       "select": [
        [
         { "params": [ "message_count" ], "type": "mean" }
        ]
       ],
       "tags": "{host =~ \"^$server$\"}"
      }
     ]
    },
    {
     "title": "Client requeue",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1483 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_channel - $tag_topic",
       "expr": "median(nsq_client_requeue_count{host =~ \"^$server$\"}) by (host,channel,topic)",
       "groupBy": " by (host,channel,topic)",
       "legendFormat": "{{host}}: {{channel}} - {{topic}}",
       "measurement": "nsq_client",
       "query": "SELECT mean(\"requeue_count\") FROM \"nsq_client\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), * fill(null)",
       "select": [
        [
         { "params": [ "requeue_count" ], "type": "mean" }
        ]
       ],
       "tags": "{host =~ \"^$server$\"}"
      }
     ]
    },
    {
     "title": "Client inflight",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1490 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_channel - $tag_topic",
       "expr": "median(nsq_client_inflight_count{host =~ \"^$server$\"}) by (host,channel,topic)",
       "groupBy": " by (host,channel,topic)",
       "legendFormat": "{{host}}: {{channel}} - {{topic}}",
       "measurement": "nsq_client",
       "query": "SELECT mean(\"inflight_count\") FROM \"nsq_client\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), * fill(null)",
       "select": [
        [
         { "params": [ "inflight_count" ], "type": "mean" }
        ]
       ],
       "tags": "{host =~ \"^$server$\"}"
      }
     ]
    },
    {
     "title": "Client ready",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1490 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_channel - $tag_topic",
       "expr": "median(nsq_client_ready_count{host =~ \"^$server$\"}) by (host,channel,topic)",
       "groupBy": " by (host,channel,topic)",
       "legendFormat": "{{host}}: {{channel}} - {{topic}}",
       "measurement": "nsq_client",
       "query": "SELECT mean(\"ready_count\") FROM \"nsq_client\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), * fill(null)",
       "select": [
        [
         { "params": [ "ready_count" ], "type": "mean" }
        ]
       ],
       "tags": "{host =~ \"^$server$\"}"
      }
     ]
    },
    {
     "title": "Client finish",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1497 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_channel - $tag_topic",
       "expr": "median(nsq_client_finish_count{host =~ \"^$server$\"}) by (host,channel,topic)",
       "groupBy": " by (host,channel,topic)",
       "legendFormat": "{{host}}: {{channel}} - {{topic}}",
       "measurement": "nsq_client",
       "query": "SELECT mean(\"finish_count\") FROM \"nsq_client\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), * fill(null)",
       "select": [
        [
         { "params": [ "finish_count" ], "type": "mean" }
        ]
       ],
       "tags": "{host =~ \"^$server$\"}"
      }
     ]
    },
    {
     "title": "Server topics",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1497 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "expr": "median(nsq_server_topic_count{host =~ \"^$server$\"}) by (host)",
       "groupBy": " by (host)",
       "legendFormat": "{{host}}",
       "measurement": "nsq_server",
       "query": "SELECT mean(\"topic_count\") FROM \"nsq_server\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), * fill(null)",
       "select": [
        [
         { "params": [ "topic_count" ], "type": "mean" }
        ]
       ],
       "tags": "{host =~ \"^$server$\"}"
      }
     ]
    },
    {
     "title": "Topic channels",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1504 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_topic",
       "expr": "median(nsq_topic_channel_count{host =~ \"^$server$\"}) by (host,topic)",
       "groupBy": " by (host,topic)",
       "legendFormat": "{{host}}: {{topic}}",
       "measurement": "nsq_topic",
       "query": "SELECT mean(\"channel_count\") FROM \"nsq_topic\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), * fill(null)",
       "select": [
        [
         { "params": [ "channel_count" ], "type": "mean" }
        ]
       ],
       "tags": "{host =~ \"^$server$\"}"
      }
     ]
    },
    {
     "title": "Topic messages",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1504 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_topic",
       "expr": "median(nsq_topic_message_count{host =~ \"^$server$\"}) by (host,topic)",
       "groupBy": " by (host,topic)",
       "legendFormat": "{{host}}: {{topic}}",
       "measurement": "nsq_topic",
       "query": "SELECT mean(\"message_count\") FROM \"nsq_topic\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), * fill(null)",
       "select": [
        [
         { "params": [ "message_count" ], "type": "mean" }
        ]
       ],
       "tags": "{host =~ \"^$server$\"}"
      }
     ]
    }
   ]
  }
 ]
}