groups:
  - name: alert.rules
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of first job {{ $labels.job }} has been down for more than 1 minute'
        summary: 'Instance {{ $labels.instance }} down'

    - alert: High UI HTTP response time
      expr: quantile(0.95, rate(ui_request_response_time_bucket[1m])) > 0.2
      for: 10s
      labels:
        severity: page
      annotations:
        description: 'UI HTTP response time has been high for more than 10 seconds'
        summary: 'High UI HTTP response time'
